linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: internal/db/models\.go
      linters:
        - govet
      text: "fieldalignment"
    - path: internal/db/.*_test\.go
      linters:
        - govet
      text: "fieldalignment"
    - path: internal/db/seed\.go
      linters:
        - govet
      text: "fieldalignment"

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    confidence: 0.8
  govet:
    enable-all: true 