run:
  tests: true

linters:
  enable:
    - govet
    - unused
    - gosimple
    - staticcheck
    - ineffassign
    - typecheck
    - misspell
    - gofmt
    - goimports
    - revive
    - errcheck
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - gocognit
    - bodyclose
    - gocritic
    - godot
    - godox
    - goheader
    - gofumpt
    - gomodguard
    - goprintffuncname
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - stylecheck
    - tparallel
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - govet
        - testpackage
        - wsl
        - lll
        - gocognit
        - godox
        - revive
        - noctx
    - path: \.go$
      linters:
        - godox
        - godot
        - revive
        - gofumpt
        - nolintlint 